using System;
using System.Runtime.InteropServices;

namespace SDL
{
    public enum Keycode
    {
        Unknown = 0,

        Return = '\r',
        Escape = 27, // '\033'
        Backspace = '\b',
        Tab = '\t',
        Space = ' ',
        Exclaim = '!',
        QuoteDbl = '"',
        Hash = '#',
        Percent = '%',
        Dollar = '$',
        Ampersand = '&',
        Quote = '\'',
        LeftParen = '(',
        RightParen = ')',
        Asterisk = '*',
        Plus = '+',
        Comma = ',',
        Minus = '-',
        Period = '.',
        Slash = '/',
        _0 = '0',
        _1 = '1',
        _2 = '2',
        _3 = '3',
        _4 = '4',
        _5 = '5',
        _6 = '6',
        _7 = '7',
        _8 = '8',
        _9 = '9',
        Colon = ':',
        Semicolon = ';',
        Less = '<',
        Equals = '=',
        Greater = '>',
        Question = '?',
        At = '@',
        /*
          Skip uppercase letters
        */
        LeftBracket = '[',
        Backslash = '\\',
        RightBracket = ']',
        Caret = '^',
        Underscore = '_',
        Backquote = '`',
        SDLK_a = 'a',
        SDLK_b = 'b',
        SDLK_c = 'c',
        SDLK_d = 'd',
        SDLK_e = 'e',
        SDLK_f = 'f',
        SDLK_g = 'g',
        SDLK_h = 'h',
        SDLK_i = 'i',
        SDLK_j = 'j',
        SDLK_k = 'k',
        SDLK_l = 'l',
        SDLK_m = 'm',
        SDLK_n = 'n',
        SDLK_o = 'o',
        SDLK_p = 'p',
        SDLK_q = 'q',
        SDLK_r = 'r',
        SDLK_s = 's',
        SDLK_t = 't',
        SDLK_u = 'u',
        SDLK_v = 'v',
        SDLK_w = 'w',
        SDLK_x = 'x',
        SDLK_y = 'y',
        SDLK_z = 'z',

        Capslock = (int)Scancode.CapsLock | Scancode.Mask,

        F1 = (int)Scancode.F1 | Scancode.Mask,
        F2 = (int)Scancode.F2 | Scancode.Mask,
        F3 = (int)Scancode.F3 | Scancode.Mask,
        F4 = (int)Scancode.F4 | Scancode.Mask,
        F5 = (int)Scancode.F5 | Scancode.Mask,
        F6 = (int)Scancode.F6 | Scancode.Mask,
        F7 = (int)Scancode.F7 | Scancode.Mask,
        F8 = (int)Scancode.F8 | Scancode.Mask,
        F9 = (int)Scancode.F9 | Scancode.Mask,
        F10 = (int)Scancode.F10 | Scancode.Mask,
        F11 = (int)Scancode.F11 | Scancode.Mask,
        F12 = (int)Scancode.F12 | Scancode.Mask,

        Printscreen = (int)Scancode.PrintScreen | Scancode.Mask,
        Scrolllock = (int)Scancode.ScrollLock | Scancode.Mask,
        Pause = (int)Scancode.Pause | Scancode.Mask,
        Insert = (int)Scancode.Insert | Scancode.Mask,
        Home = (int)Scancode.Home | Scancode.Mask,
        Pageup = (int)Scancode.PageUp | Scancode.Mask,
        Delete = 127,
        End = (int)Scancode.End | Scancode.Mask,
        Pagedown = (int)Scancode.PageDown | Scancode.Mask,
        Right = (int)Scancode.Right | Scancode.Mask,
        Left = (int)Scancode.Left | Scancode.Mask,
        Down = (int)Scancode.Down | Scancode.Mask,
        Up = (int)Scancode.Up | Scancode.Mask,

        NumLockClear = (int)Scancode.NumLockClear | Scancode.Mask,
        KpDivide = (int)Scancode.KpDivide | Scancode.Mask,
        KpMultiply = (int)Scancode.KpMultiply | Scancode.Mask,
        KpMinus = (int)Scancode.KpMinus | Scancode.Mask,
        KpPlus = (int)Scancode.KpPlus | Scancode.Mask,
        KpEnter = (int)Scancode.KpEnter | Scancode.Mask,
        Kp1 = (int)Scancode.Kp1 | Scancode.Mask,
        Kp2 = (int)Scancode.Kp2 | Scancode.Mask,
        Kp3 = (int)Scancode.Kp3 | Scancode.Mask,
        Kp4 = (int)Scancode.Kp4 | Scancode.Mask,
        Kp5 = (int)Scancode.Kp5 | Scancode.Mask,
        Kp6 = (int)Scancode.Kp6 | Scancode.Mask,
        Kp7 = (int)Scancode.Kp7 | Scancode.Mask,
        Kp8 = (int)Scancode.Kp8 | Scancode.Mask,
        Kp9 = (int)Scancode.Kp9 | Scancode.Mask,
        Kp0 = (int)Scancode.Kp0 | Scancode.Mask,
        KpPeriod = (int)Scancode.KpPeriod | Scancode.Mask,

        Application = (int)Scancode.Application | Scancode.Mask,
        Power = (int)Scancode.Power | Scancode.Mask,
        KpEquals = (int)Scancode.KpEquals | Scancode.Mask,
        F13 = (int)Scancode.F13 | Scancode.Mask,
        F14 = (int)Scancode.F14 | Scancode.Mask,
        F15 = (int)Scancode.F15 | Scancode.Mask,
        F16 = (int)Scancode.F16 | Scancode.Mask,
        F17 = (int)Scancode.F17 | Scancode.Mask,
        F18 = (int)Scancode.F18 | Scancode.Mask,
        F19 = (int)Scancode.F19 | Scancode.Mask,
        F20 = (int)Scancode.F20 | Scancode.Mask,
        F21 = (int)Scancode.F21 | Scancode.Mask,
        F22 = (int)Scancode.F22 | Scancode.Mask,
        F23 = (int)Scancode.F23 | Scancode.Mask,
        F24 = (int)Scancode.F24 | Scancode.Mask,
        Execute = (int)Scancode.Execute | Scancode.Mask,
        Help = (int)Scancode.Help | Scancode.Mask,
        Menu = (int)Scancode.Menu | Scancode.Mask,
        Select = (int)Scancode.Select | Scancode.Mask,
        Stop = (int)Scancode.Stop | Scancode.Mask,
        Again = (int)Scancode.Again | Scancode.Mask,
        Undo = (int)Scancode.Undo | Scancode.Mask,
        Cut = (int)Scancode.Cut | Scancode.Mask,
        Copy = (int)Scancode.Copy | Scancode.Mask,
        Paste = (int)Scancode.Paste | Scancode.Mask,
        Find = (int)Scancode.Find | Scancode.Mask,
        Mute = (int)Scancode.Mute | Scancode.Mask,
        VolumeUp = (int)Scancode.VolumeUp | Scancode.Mask,
        VolumeDown = (int)Scancode.VolumeDown | Scancode.Mask,
        KpComma = (int)Scancode.KpComma | Scancode.Mask,
        KpEqualsAs400 = (int)Scancode.KpEqualsAs400 | Scancode.Mask,

        AltErase = (int)Scancode.AltErase | Scancode.Mask,
        SysReq = (int)Scancode.SysReq | Scancode.Mask,
        Cancel = (int)Scancode.Cancel | Scancode.Mask,
        Clear = (int)Scancode.Clear | Scancode.Mask,
        Prior = (int)Scancode.Prior | Scancode.Mask,
        Return2 = (int)Scancode.Return2 | Scancode.Mask,
        Separator = (int)Scancode.Separator | Scancode.Mask,
        Out = (int)Scancode.Out | Scancode.Mask,
        Oper = (int)Scancode.Oper | Scancode.Mask,
        ClearAgain = (int)Scancode.ClearAgain | Scancode.Mask,
        CrSel = (int)Scancode.CrSel | Scancode.Mask,
        ExSel = (int)Scancode.ExSel | Scancode.Mask,

        Kp00 = (int)Scancode.Kp00 | Scancode.Mask,
        Kp000 = (int)Scancode.Kp000 | Scancode.Mask,
        ThousandsSeparator = (int)Scancode.ThousandsSeparator | Scancode.Mask,
        DecimalSeparator = (int)Scancode.DecimalSeparator | Scancode.Mask,
        CurrencyUnit = (int)Scancode.CurrencyUnit | Scancode.Mask,
        CurrencySubunit = (int)Scancode.CurrencySubunit | Scancode.Mask,
        KpLeftParen = (int)Scancode.KpLeftParen | Scancode.Mask,
        KpRightParen = (int)Scancode.KpRightParen | Scancode.Mask,
        KpLeftBrace = (int)Scancode.KpLeftBrace | Scancode.Mask,
        KpRightBrace = (int)Scancode.KpRightBrace | Scancode.Mask,
        KpTab = (int)Scancode.KpTab | Scancode.Mask,
        KpBackspace = (int)Scancode.KpBackspace | Scancode.Mask,
        KpA = (int)Scancode.KpA | Scancode.Mask,
        KpB = (int)Scancode.KpB | Scancode.Mask,
        KpC = (int)Scancode.KpC | Scancode.Mask,
        KpD = (int)Scancode.KpD | Scancode.Mask,
        KpE = (int)Scancode.KpE | Scancode.Mask,
        KpF = (int)Scancode.KpF | Scancode.Mask,
        KpXor = (int)Scancode.KpXor | Scancode.Mask,
        KpPower = (int)Scancode.KpPower | Scancode.Mask,
        KpPercent = (int)Scancode.KpPercent | Scancode.Mask,
        KpLess = (int)Scancode.KpLess | Scancode.Mask,
        KpGreater = (int)Scancode.KpGreater | Scancode.Mask,
        KpAmpersand = (int)Scancode.KpAmpersand | Scancode.Mask,
        KpDblAmpersand = (int)Scancode.KpDblAmpersand | Scancode.Mask,
        KpVerticalBar = (int)Scancode.KpVerticalBar | Scancode.Mask,
        KpDblVerticalBar = (int)Scancode.KpDblVerticalBar | Scancode.Mask,
        KpColon = (int)Scancode.KpColon | Scancode.Mask,
        KpHash = (int)Scancode.KpHash | Scancode.Mask,
        KpSpace = (int)Scancode.KpSpace | Scancode.Mask,
        KpAt = (int)Scancode.KpAt | Scancode.Mask,
        KpExclam = (int)Scancode.KpExclam | Scancode.Mask,
        KpMemStore = (int)Scancode.KpMemStore | Scancode.Mask,
        KpMemRecall = (int)Scancode.KpMemRecall | Scancode.Mask,
        KpMemClear = (int)Scancode.KpMemClear | Scancode.Mask,
        KpMemAdd = (int)Scancode.KpMemAdd | Scancode.Mask,
        KpMemSubtract = (int)Scancode.KpMemSubtract | Scancode.Mask,
        KpMemMultiply = (int)Scancode.KpMemMultiply | Scancode.Mask,
        KpMemDivide = (int)Scancode.KpMemDivide | Scancode.Mask,
        KpPlusMinus = (int)Scancode.KpPlusMinus | Scancode.Mask,
        KpClear = (int)Scancode.KpClear | Scancode.Mask,
        KpClearEntry = (int)Scancode.KpClearEntry | Scancode.Mask,
        KpBinary = (int)Scancode.KpBinary | Scancode.Mask,
        KpOctal = (int)Scancode.KpOctal | Scancode.Mask,
        KpDecimal = (int)Scancode.KpDecimal | Scancode.Mask,
        KpHexadecimal = (int)Scancode.KpHexadecimal | Scancode.Mask,

        LCtrl = (int)Scancode.LCtrl | Scancode.Mask,
        LShift = (int)Scancode.LShift | Scancode.Mask,
        LAlt = (int)Scancode.LAlt | Scancode.Mask,
        LGui = (int)Scancode.LGui | Scancode.Mask,
        RCtrl = (int)Scancode.RCtrl | Scancode.Mask,
        RShift = (int)Scancode.RShift | Scancode.Mask,
        RAlt = (int)Scancode.RAlt | Scancode.Mask,
        RGui = (int)Scancode.RGui | Scancode.Mask,

        Mode = (int)Scancode.Mode | Scancode.Mask,

        AudioNext = (int)Scancode.AudioNext | Scancode.Mask,
        AudioPrev = (int)Scancode.AudioPrev | Scancode.Mask,
        AudioStop = (int)Scancode.AudioStop | Scancode.Mask,
        AudioPlay = (int)Scancode.AudioPlay | Scancode.Mask,
        AudioMute = (int)Scancode.AudioMute | Scancode.Mask,
        MediaSelect = (int)Scancode.MediaSelect | Scancode.Mask,
        Www = (int)Scancode.Www | Scancode.Mask,
        Mail = (int)Scancode.Mail | Scancode.Mask,
        Calculator = (int)Scancode.Calculator | Scancode.Mask,
        Computer = (int)Scancode.Computer | Scancode.Mask,
        AcSearch = (int)Scancode.AcSearch | Scancode.Mask,
        AcHome = (int)Scancode.AcHome | Scancode.Mask,
        AcBack = (int)Scancode.AcBack | Scancode.Mask,
        AcForward = (int)Scancode.AcForward | Scancode.Mask,
        AcStop = (int)Scancode.AcStop | Scancode.Mask,
        AcRefresh = (int)Scancode.AcRefresh | Scancode.Mask,
        AcBookmarks = (int)Scancode.AcBookmarks | Scancode.Mask,

        BrightnessDown =
        (int)Scancode.BrightnessDown | Scancode.Mask,
        BrightnessUp = (int)Scancode.BrightnessUp | Scancode.Mask,
        DisplaySwitch = (int)Scancode.DisplaySwitch | Scancode.Mask,
        KbdIllumToggle =
        (int)Scancode.KbdIllumToggle | Scancode.Mask,
        KbdIllumDown = (int)Scancode.KbdIllumDown | Scancode.Mask,
        KbdIllumUp = (int)Scancode.KbdIllumUp | Scancode.Mask,
        Eject = (int)Scancode.Eject | Scancode.Mask,
        Sleep = (int)Scancode.Sleep | Scancode.Mask
    }

    /* Key modifiers (bitfield) */
    [Flags]
    public enum Keymod : ushort
    {
        None = 0x0000,
        LShift = 0x0001,
        RShift = 0x0002,
        LCtrl = 0x0040,
        RCtrl = 0x0080,
        LAlt = 0x0100,
        RAlt = 0x0200,
        LGui = 0x0400,
        RGui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Reserved = 0x8000,

        /* These are defines in the SDL headers */
        Ctrl = (LCtrl | RCtrl),
        Shift = (LShift | RShift),
        Alt = (LAlt | RAlt),
        Gui = (LGui | RGui)
    }
}
