using System;
using System.Runtime.InteropServices;

namespace SDL
{
    public enum KeyCode
    {
        Unknown = 0,

        Return = '\r',
        Escape = 27, // '\033'
        Backspace = '\b',
        Tab = '\t',
        Space = ' ',
        Exclaim = '!',
        QuoteDbl = '"',
        Hash = '#',
        Percent = '%',
        Dollar = '$',
        Ampersand = '&',
        Quote = '\'',
        LeftParen = '(',
        RightParen = ')',
        Asterisk = '*',
        Plus = '+',
        Comma = ',',
        Minus = '-',
        Period = '.',
        Slash = '/',
        _0 = '0',
        _1 = '1',
        _2 = '2',
        _3 = '3',
        _4 = '4',
        _5 = '5',
        _6 = '6',
        _7 = '7',
        _8 = '8',
        _9 = '9',
        Colon = ':',
        Semicolon = ';',
        Less = '<',
        Equals = '=',
        Greater = '>',
        Question = '?',
        At = '@',
        /*
          Skip uppercase letters
        */
        LeftBracket = '[',
        Backslash = '\\',
        RightBracket = ']',
        Caret = '^',
        Underscore = '_',
        Backquote = '`',
        SDLK_a = 'a',
        SDLK_b = 'b',
        SDLK_c = 'c',
        SDLK_d = 'd',
        SDLK_e = 'e',
        SDLK_f = 'f',
        SDLK_g = 'g',
        SDLK_h = 'h',
        SDLK_i = 'i',
        SDLK_j = 'j',
        SDLK_k = 'k',
        SDLK_l = 'l',
        SDLK_m = 'm',
        SDLK_n = 'n',
        SDLK_o = 'o',
        SDLK_p = 'p',
        SDLK_q = 'q',
        SDLK_r = 'r',
        SDLK_s = 's',
        SDLK_t = 't',
        SDLK_u = 'u',
        SDLK_v = 'v',
        SDLK_w = 'w',
        SDLK_x = 'x',
        SDLK_y = 'y',
        SDLK_z = 'z',

        Capslock = (int)ScanCode.CapsLock | ScanCode.Mask,

        F1 = (int)ScanCode.F1 | ScanCode.Mask,
        F2 = (int)ScanCode.F2 | ScanCode.Mask,
        F3 = (int)ScanCode.F3 | ScanCode.Mask,
        F4 = (int)ScanCode.F4 | ScanCode.Mask,
        F5 = (int)ScanCode.F5 | ScanCode.Mask,
        F6 = (int)ScanCode.F6 | ScanCode.Mask,
        F7 = (int)ScanCode.F7 | ScanCode.Mask,
        F8 = (int)ScanCode.F8 | ScanCode.Mask,
        F9 = (int)ScanCode.F9 | ScanCode.Mask,
        F10 = (int)ScanCode.F10 | ScanCode.Mask,
        F11 = (int)ScanCode.F11 | ScanCode.Mask,
        F12 = (int)ScanCode.F12 | ScanCode.Mask,

        Printscreen = (int)ScanCode.PrintScreen | ScanCode.Mask,
        Scrolllock = (int)ScanCode.ScrollLock | ScanCode.Mask,
        Pause = (int)ScanCode.Pause | ScanCode.Mask,
        Insert = (int)ScanCode.Insert | ScanCode.Mask,
        Home = (int)ScanCode.Home | ScanCode.Mask,
        Pageup = (int)ScanCode.PageUp | ScanCode.Mask,
        Delete = 127,
        End = (int)ScanCode.End | ScanCode.Mask,
        Pagedown = (int)ScanCode.PageDown | ScanCode.Mask,
        Right = (int)ScanCode.Right | ScanCode.Mask,
        Left = (int)ScanCode.Left | ScanCode.Mask,
        Down = (int)ScanCode.Down | ScanCode.Mask,
        Up = (int)ScanCode.Up | ScanCode.Mask,

        NumLockClear = (int)ScanCode.NumLockClear | ScanCode.Mask,
        KpDivide = (int)ScanCode.KpDivide | ScanCode.Mask,
        KpMultiply = (int)ScanCode.KpMultiply | ScanCode.Mask,
        KpMinus = (int)ScanCode.KpMinus | ScanCode.Mask,
        KpPlus = (int)ScanCode.KpPlus | ScanCode.Mask,
        KpEnter = (int)ScanCode.KpEnter | ScanCode.Mask,
        Kp1 = (int)ScanCode.Kp1 | ScanCode.Mask,
        Kp2 = (int)ScanCode.Kp2 | ScanCode.Mask,
        Kp3 = (int)ScanCode.Kp3 | ScanCode.Mask,
        Kp4 = (int)ScanCode.Kp4 | ScanCode.Mask,
        Kp5 = (int)ScanCode.Kp5 | ScanCode.Mask,
        Kp6 = (int)ScanCode.Kp6 | ScanCode.Mask,
        Kp7 = (int)ScanCode.Kp7 | ScanCode.Mask,
        Kp8 = (int)ScanCode.Kp8 | ScanCode.Mask,
        Kp9 = (int)ScanCode.Kp9 | ScanCode.Mask,
        Kp0 = (int)ScanCode.Kp0 | ScanCode.Mask,
        KpPeriod = (int)ScanCode.KpPeriod | ScanCode.Mask,

        Application = (int)ScanCode.Application | ScanCode.Mask,
        Power = (int)ScanCode.Power | ScanCode.Mask,
        KpEquals = (int)ScanCode.KpEquals | ScanCode.Mask,
        F13 = (int)ScanCode.F13 | ScanCode.Mask,
        F14 = (int)ScanCode.F14 | ScanCode.Mask,
        F15 = (int)ScanCode.F15 | ScanCode.Mask,
        F16 = (int)ScanCode.F16 | ScanCode.Mask,
        F17 = (int)ScanCode.F17 | ScanCode.Mask,
        F18 = (int)ScanCode.F18 | ScanCode.Mask,
        F19 = (int)ScanCode.F19 | ScanCode.Mask,
        F20 = (int)ScanCode.F20 | ScanCode.Mask,
        F21 = (int)ScanCode.F21 | ScanCode.Mask,
        F22 = (int)ScanCode.F22 | ScanCode.Mask,
        F23 = (int)ScanCode.F23 | ScanCode.Mask,
        F24 = (int)ScanCode.F24 | ScanCode.Mask,
        Execute = (int)ScanCode.Execute | ScanCode.Mask,
        Help = (int)ScanCode.Help | ScanCode.Mask,
        Menu = (int)ScanCode.Menu | ScanCode.Mask,
        Select = (int)ScanCode.Select | ScanCode.Mask,
        Stop = (int)ScanCode.Stop | ScanCode.Mask,
        Again = (int)ScanCode.Again | ScanCode.Mask,
        Undo = (int)ScanCode.Undo | ScanCode.Mask,
        Cut = (int)ScanCode.Cut | ScanCode.Mask,
        Copy = (int)ScanCode.Copy | ScanCode.Mask,
        Paste = (int)ScanCode.Paste | ScanCode.Mask,
        Find = (int)ScanCode.Find | ScanCode.Mask,
        Mute = (int)ScanCode.Mute | ScanCode.Mask,
        VolumeUp = (int)ScanCode.VolumeUp | ScanCode.Mask,
        VolumeDown = (int)ScanCode.VolumeDown | ScanCode.Mask,
        KpComma = (int)ScanCode.KpComma | ScanCode.Mask,
        KpEqualsAs400 = (int)ScanCode.KpEqualsAs400 | ScanCode.Mask,

        AltErase = (int)ScanCode.AltErase | ScanCode.Mask,
        SysReq = (int)ScanCode.SysReq | ScanCode.Mask,
        Cancel = (int)ScanCode.Cancel | ScanCode.Mask,
        Clear = (int)ScanCode.Clear | ScanCode.Mask,
        Prior = (int)ScanCode.Prior | ScanCode.Mask,
        Return2 = (int)ScanCode.Return2 | ScanCode.Mask,
        Separator = (int)ScanCode.Separator | ScanCode.Mask,
        Out = (int)ScanCode.Out | ScanCode.Mask,
        Oper = (int)ScanCode.Oper | ScanCode.Mask,
        ClearAgain = (int)ScanCode.ClearAgain | ScanCode.Mask,
        CrSel = (int)ScanCode.CrSel | ScanCode.Mask,
        ExSel = (int)ScanCode.ExSel | ScanCode.Mask,

        Kp00 = (int)ScanCode.Kp00 | ScanCode.Mask,
        Kp000 = (int)ScanCode.Kp000 | ScanCode.Mask,
        ThousandsSeparator = (int)ScanCode.ThousandsSeparator | ScanCode.Mask,
        DecimalSeparator = (int)ScanCode.DecimalSeparator | ScanCode.Mask,
        CurrencyUnit = (int)ScanCode.CurrencyUnit | ScanCode.Mask,
        CurrencySubunit = (int)ScanCode.CurrencySubunit | ScanCode.Mask,
        KpLeftParen = (int)ScanCode.KpLeftParen | ScanCode.Mask,
        KpRightParen = (int)ScanCode.KpRightParen | ScanCode.Mask,
        KpLeftBrace = (int)ScanCode.KpLeftBrace | ScanCode.Mask,
        KpRightBrace = (int)ScanCode.KpRightBrace | ScanCode.Mask,
        KpTab = (int)ScanCode.KpTab | ScanCode.Mask,
        KpBackspace = (int)ScanCode.KpBackspace | ScanCode.Mask,
        KpA = (int)ScanCode.KpA | ScanCode.Mask,
        KpB = (int)ScanCode.KpB | ScanCode.Mask,
        KpC = (int)ScanCode.KpC | ScanCode.Mask,
        KpD = (int)ScanCode.KpD | ScanCode.Mask,
        KpE = (int)ScanCode.KpE | ScanCode.Mask,
        KpF = (int)ScanCode.KpF | ScanCode.Mask,
        KpXor = (int)ScanCode.KpXor | ScanCode.Mask,
        KpPower = (int)ScanCode.KpPower | ScanCode.Mask,
        KpPercent = (int)ScanCode.KpPercent | ScanCode.Mask,
        KpLess = (int)ScanCode.KpLess | ScanCode.Mask,
        KpGreater = (int)ScanCode.KpGreater | ScanCode.Mask,
        KpAmpersand = (int)ScanCode.KpAmpersand | ScanCode.Mask,
        KpDblAmpersand = (int)ScanCode.KpDblAmpersand | ScanCode.Mask,
        KpVerticalBar = (int)ScanCode.KpVerticalBar | ScanCode.Mask,
        KpDblVerticalBar = (int)ScanCode.KpDblVerticalBar | ScanCode.Mask,
        KpColon = (int)ScanCode.KpColon | ScanCode.Mask,
        KpHash = (int)ScanCode.KpHash | ScanCode.Mask,
        KpSpace = (int)ScanCode.KpSpace | ScanCode.Mask,
        KpAt = (int)ScanCode.KpAt | ScanCode.Mask,
        KpExclam = (int)ScanCode.KpExclam | ScanCode.Mask,
        KpMemStore = (int)ScanCode.KpMemStore | ScanCode.Mask,
        KpMemRecall = (int)ScanCode.KpMemRecall | ScanCode.Mask,
        KpMemClear = (int)ScanCode.KpMemClear | ScanCode.Mask,
        KpMemAdd = (int)ScanCode.KpMemAdd | ScanCode.Mask,
        KpMemSubtract = (int)ScanCode.KpMemSubtract | ScanCode.Mask,
        KpMemMultiply = (int)ScanCode.KpMemMultiply | ScanCode.Mask,
        KpMemDivide = (int)ScanCode.KpMemDivide | ScanCode.Mask,
        KpPlusMinus = (int)ScanCode.KpPlusMinus | ScanCode.Mask,
        KpClear = (int)ScanCode.KpClear | ScanCode.Mask,
        KpClearEntry = (int)ScanCode.KpClearEntry | ScanCode.Mask,
        KpBinary = (int)ScanCode.KpBinary | ScanCode.Mask,
        KpOctal = (int)ScanCode.KpOctal | ScanCode.Mask,
        KpDecimal = (int)ScanCode.KpDecimal | ScanCode.Mask,
        KpHexadecimal = (int)ScanCode.KpHexadecimal | ScanCode.Mask,

        LCtrl = (int)ScanCode.LCtrl | ScanCode.Mask,
        LShift = (int)ScanCode.LShift | ScanCode.Mask,
        LAlt = (int)ScanCode.LAlt | ScanCode.Mask,
        LGui = (int)ScanCode.LGui | ScanCode.Mask,
        RCtrl = (int)ScanCode.RCtrl | ScanCode.Mask,
        RShift = (int)ScanCode.RShift | ScanCode.Mask,
        RAlt = (int)ScanCode.RAlt | ScanCode.Mask,
        RGui = (int)ScanCode.RGui | ScanCode.Mask,

        Mode = (int)ScanCode.Mode | ScanCode.Mask,

        AudioNext = (int)ScanCode.AudioNext | ScanCode.Mask,
        AudioPrev = (int)ScanCode.AudioPrev | ScanCode.Mask,
        AudioStop = (int)ScanCode.AudioStop | ScanCode.Mask,
        AudioPlay = (int)ScanCode.AudioPlay | ScanCode.Mask,
        AudioMute = (int)ScanCode.AudioMute | ScanCode.Mask,
        MediaSelect = (int)ScanCode.MediaSelect | ScanCode.Mask,
        Www = (int)ScanCode.Www | ScanCode.Mask,
        Mail = (int)ScanCode.Mail | ScanCode.Mask,
        Calculator = (int)ScanCode.Calculator | ScanCode.Mask,
        Computer = (int)ScanCode.Computer | ScanCode.Mask,
        AcSearch = (int)ScanCode.AcSearch | ScanCode.Mask,
        AcHome = (int)ScanCode.AcHome | ScanCode.Mask,
        AcBack = (int)ScanCode.AcBack | ScanCode.Mask,
        AcForward = (int)ScanCode.AcForward | ScanCode.Mask,
        AcStop = (int)ScanCode.AcStop | ScanCode.Mask,
        AcRefresh = (int)ScanCode.AcRefresh | ScanCode.Mask,
        AcBookmarks = (int)ScanCode.AcBookmarks | ScanCode.Mask,

        BrightnessDown =
        (int)ScanCode.BrightnessDown | ScanCode.Mask,
        BrightnessUp = (int)ScanCode.BrightnessUp | ScanCode.Mask,
        DisplaySwitch = (int)ScanCode.DisplaySwitch | ScanCode.Mask,
        KbdIllumToggle =
        (int)ScanCode.KbdIllumToggle | ScanCode.Mask,
        KbdIllumDown = (int)ScanCode.KbdIllumDown | ScanCode.Mask,
        KbdIllumUp = (int)ScanCode.KbdIllumUp | ScanCode.Mask,
        Eject = (int)ScanCode.Eject | ScanCode.Mask,
        Sleep = (int)ScanCode.Sleep | ScanCode.Mask
    }

    /* Key modifiers (bitfield) */
    [Flags]
    public enum KeyMod : ushort
    {
        None = 0x0000,
        LShift = 0x0001,
        RShift = 0x0002,
        LCtrl = 0x0040,
        RCtrl = 0x0080,
        LAlt = 0x0100,
        RAlt = 0x0200,
        LGui = 0x0400,
        RGui = 0x0800,
        Num = 0x1000,
        Caps = 0x2000,
        Mode = 0x4000,
        Reserved = 0x8000,

        /* These are defines in the SDL headers */
        Ctrl = (LCtrl | RCtrl),
        Shift = (LShift | RShift),
        Alt = (LAlt | RAlt),
        Gui = (LGui | RGui)
    }
}
